apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
    {{- include "pulse.web.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "pulse.web.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: http
